### ISSUE TITLE
Does not build because of node-sass version

### ISSUE THREAD

**Issue by idseefeld** [andreasbm/web-config#16]
Hey,

I got a build issue for your router-slot because of its dependency to this package.
So I tried to build this and found an issue here too.
I just tried to upgrade the version of node-sass to current: `^8.0.0`
Than this installs all node_modules and build.

May be other dependencies should also be updated?

Best regards,
Dirk

**Comment by idseefeld** [comment]
Looks like a new Python version (3.11) was the issue. Move back to version 3.8.7 and it installs.

**Comment by christophe-g** [comment]
@idseefeld - I think this should be reopened as the root cause is not resolved.

I got the same situation with router-slot not being able to build 

@andreasbm - is it possible to bump dependencies on this repo + on router-slot for a streamlined build process ?
